### ISSUE TITLE
not able to create VM image using Imagefactory 

### ISSUE THREAD

**Issue by brijeshverma** [redhat-imaging/imagefactory#302]
Hello , I am following below steps to create the VM image using imagefactory comand but its not working properly .Please can anyone tell me the proper steps to create the VM image using imagefactory . I already spend 2 weeks on imagefactory R&D

I am using below steps

 running imagectory_dev_setup.sh file under  /imagefactory/scripts
the starting imagefactory service  ./imagefactoryd

Imagefactory --debug target_image --target f16_64.tdl EC2

TDl file 

<template>
  <name>f17_x86_64</name>
  <os>
    <name>Fedora</name>
    <version>17</version>
    <arch>x86_64</arch>
    <install type='iso'>
      <iso>http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso</iso>
    </install>
    <rootpw>password</rootpw>
  </os>
</template>

see the belo logs

root@sudhir-virtual-machine:/home/sudhir/imagefactory# imagefactory --debug target_image --template f16_64.tdl EC2
2013-07-09 12:29:26,556 DEBUG root thread(MainThread) Message: Unable to find python module, faulthandler... multi-thread tracebacks will not be available. See http://pypi.python.org/pypi/faulthandler/ for more information.
2013-07-09 12:29:26,593 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (TinMan) loaded...
2013-07-09 12:29:26,599 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (RHEVM) loaded...
2013-07-09 12:29:26,604 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (MockOS) loaded...
2013-07-09 12:29:26,609 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (OpenStack) loaded...
2013-07-09 12:29:26,614 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (MockCloud) loaded...
2013-07-09 12:29:26,624 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (vSphere) loaded...
2013-07-09 12:29:26,634 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (EC2) loaded...
2013-07-09 12:29:26,788 DEBUG imgfac.Builder.Builder thread(MainThread) Message: No SecondaryDispatcher present - Use of secondary factories is not enabled
2013-07-09 12:29:26,789 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Created file /var/lib/oz/isos/51977a14-2735-4804-8295-2e218072be8b.meta
2013-07-09 12:29:26,789 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Created file /var/lib/oz/isos/51977a14-2735-4804-8295-2e218072be8b.body
2013-07-09 12:29:26,789 DEBUG imgfac.PersistentImage.TargetImage thread(MainThread) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('base_image_id', 'target'))
2013-07-09 12:29:26,789 DEBUG imgfac.PersistentImage.TargetImage thread(MainThread) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('identifier', 'data', 'template', 'icicle', 'status_detail', 'status', 'percent_complete', 'parameters'))
2013-07-09 12:29:26,789 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Saved metadata for image (51977a14-2735-4804-8295-2e218072be8b): {'status': 'NEW', 'identifier': '51977a14-2735-4804-8295-2e218072be8b', 'target': 'EC2', 'parameters': {}, 'icicle': None, 'data': '/var/lib/oz/isos/51977a14-2735-4804-8295-2e218072be8b.body', 'base_image_id': None, 'status_detail': {'error': None, 'activity': 'Initializing image prior to Cloud/OS customization'}, 'template': "<template>\n  <name>f17_x86_64</name>\n  <os>\n    <name>Fedora</name>\n    <version>17</version>\n    <arch>x86_64</arch>\n    <install type='iso'>\n      <iso>http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso</iso>\n    </install>\n    <rootpw>password</rootpw>\n  </os>\n</template>\n", 'percent_complete': 0, 'type': 'TargetImage'}
2013-07-09 12:29:26,790 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Created file /var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.meta
2013-07-09 12:29:26,790 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Created file /var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body
2013-07-09 12:29:26,790 DEBUG imgfac.PersistentImage.BaseImage thread(MainThread) Message: Getting metadata in class (<class 'imgfac.BaseImage.BaseImage'>) my metadata is (())
2013-07-09 12:29:26,790 DEBUG imgfac.PersistentImage.BaseImage thread(MainThread) Message: Executing metadata in class (<class 'imgfac.BaseImage.BaseImage'>) my metadata is (('identifier', 'data', 'template', 'icicle', 'status_detail', 'status', 'percent_complete', 'parameters'))
2013-07-09 12:29:26,790 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(MainThread) Message: Saved metadata for image (9921e75c-218c-4bc9-90ab-35a2b576df5d): {'status': 'NEW', 'identifier': '9921e75c-218c-4bc9-90ab-35a2b576df5d', 'parameters': {}, 'icicle': None, 'data': '/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body', 'status_detail': {'error': None, 'activity': 'Initializing image prior to Cloud/OS customization'}, 'template': "<template>\n  <name>f17_x86_64</name>\n  <os>\n    <name>Fedora</name>\n    <version>17</version>\n    <arch>x86_64</arch>\n    <install type='iso'>\n      <iso>http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso</iso>\n    </install>\n    <rootpw>password</rootpw>\n  </os>\n</template>\n", 'percent_complete': 0, 'type': 'BaseImage'}
2013-07-09 12:29:26,799 DEBUG imgfac.PluginManager.PluginManager thread(7f42f416) Message: Attempting to match list target (['Fedora', '17', 'x86_64'])
2013-07-09 12:29:26,812 DEBUG imgfac.PersistentImage.TargetImage thread(MainThread) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('base_image_id', 'target'))
2013-07-09 12:29:26,812 DEBUG imgfac.PersistentImage.TargetImage thread(MainThread) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('identifier', 'data', 'template', 'icicle', 'status_detail', 'status', 'percent_complete', 'parameters'))
2013-07-09 12:29:26,812 DEBUG imgfac.Builder.Builder thread(b1289c2b) Message: Waiting for our BaseImage builder thread (7f42f416) to finish
2013-07-09 12:29:27,916 INFO imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: create_base_image() called for TinMan plugin - creating a BaseImage
2013-07-09 12:29:28,241 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: libvirt bridge name is virbr0
2013-07-09 12:29:28,592 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Libvirt type is qemu
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Name: factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d, UUID: 6397eb61-d012-4b78-a22b-43a3f38422af
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: MAC: 52:54:00:9e:3a:27, distro: Fedora
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: update: 17, arch: x86_64, diskimage: /var/lib/imagefactory/images/factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d.dsk
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: nicmodel: virtio, clockoffset: utc
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: mousetype: ps2, disk_bus: virtio, disk_dev: vda
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: icicletmp: /var/lib/oz/icicletmp/factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d, listen_port: 9423
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Original ISO path: /var/lib/oz/isos/Fedora17x86_64-iso.iso
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Modified ISO cache: /var/lib/oz/isos/Fedora17x86_64-iso-oz.iso
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Output ISO path: /var/lib/imagefactory/images/factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d-iso-oz.iso
2013-07-09 12:29:28,616 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: ISO content path: /var/lib/oz/isocontent/factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d-iso
2013-07-09 12:29:28,616 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Cleaning up any old Oz guest
2013-07-09 12:29:28,616 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Cleaning up guest named factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d
2013-07-09 12:29:28,617 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Generating JEOS install media
2013-07-09 12:29:28,617 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Grabbing named lock (Fedora-17-x86_64-iso)
2013-07-09 12:29:28,618 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Got named lock (Fedora-17-x86_64-iso)
2013-07-09 12:29:28,618 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Generating install media
2013-07-09 12:29:28,618 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Fetching the original media
2013-07-09 12:29:28,618 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Attempting to get the lock for /var/lib/oz/isos/Fedora17x86_64-iso.iso
2013-07-09 12:29:28,629 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Got the lock, doing the download
2013-07-09 12:29:29,317 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Fetching the original install media from http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso
l2013-07-09 12:44:27,716 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Copying ISO contents for modification
2013-07-09 12:44:27,808 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Setting up guestfs handle for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d
2013-07-09 12:44:27,809 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Adding ISO image /var/lib/oz/isos/Fedora17x86_64-iso.iso
2013-07-09 12:44:27,827 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Launching guestfs
2013-07-09 12:44:27,828 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Grabbing named lock (libguestfs_launch)
2013-07-09 12:44:27,828 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Got named lock (libguestfs_launch)
warning: Unable to get device geometry for /tmp/guestfs.hExd14/root
2013-07-09 12:45:26,922 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Releasing named lock (libguestfs_launch)
2013-07-09 12:45:26,923 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Mounting ISO
2013-07-09 12:45:27,848 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Checking if there is enough space on the filesystem
2013-07-09 12:45:27,964 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Extracting ISO contents
2013-07-09 12:46:37,737 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Putting the kickstart in place
2013-07-09 12:46:37,920 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Modifying isolinux.cfg
2013-07-09 12:46:37,921 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Generating new ISO
2013-07-09 12:46:46,426 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Cleaning up old ISO data
2013-07-09 12:46:46,546 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Releasing named lock (Fedora-17-x86_64-iso)
2013-07-09 12:46:46,547 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Generating JEOS disk image
2013-07-09 12:46:46,557 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Generating 10GB diskimage for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d
2013-07-09 12:46:47,356 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Execute JEOS install
2013-07-09 12:46:47,356 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Running install for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d
2013-07-09 12:46:47,365 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Generate XML for guest factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d with bootdev cdrom
2013-07-09 12:46:47,365 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Generated XML:
<?xml version="1.0"?>
<domain type="qemu">
  <name>factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d</name>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <uuid>6397eb61-d012-4b78-a22b-43a3f38422af</uuid>
  <clock offset="utc"/>
  <vcpu>1</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <os>
    <type>hvm</type>
    <boot dev="cdrom"/>
  </os>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <graphics port="-1" type="vnc"/>
    <interface type="bridge">
      <source bridge="virbr0"/>
      <mac address="52:54:00:9e:3a:27"/>
      <model type="virtio"/>
    </interface>
    <input bus="ps2" type="mouse"/>
    <serial type="pty">
      <target port="0"/>
    </serial>
    <serial type="tcp">
      <source mode="bind" host="127.0.0.1" service="1026"/>
      <protocol type="raw"/>
      <target port="1"/>
    </serial>
    <disk device="disk" type="file">
      <target dev="vda" bus="virtio"/>
      <source file="/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body"/>
      <driver name="qemu" type="raw"/>
    </disk>
    <disk type="file" device="cdrom">
      <source file="/var/lib/imagefactory/images/factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d-iso-oz.iso"/>
      <target dev="hdc"/>
    </disk>
  </devices>
</domain>

2013-07-09 12:46:52,270 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3600/3600
2013-07-09 12:47:02,353 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3590/3600
2013-07-09 12:47:12,394 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3580/3600
2013-07-09 12:47:22,439 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3570/3600
2013-07-09 12:47:32,485 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3560/3600
2013-07-09 12:47:42,536 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3550/3600
2013-07-09 12:47:52,578 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to finish installing, 3540/3600
2013-07-09 12:47:58,350 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Waiting for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d to complete shutdown, 10/10
2013-07-09 12:47:59,173 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Install of factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d succeeded
2013-07-09 12:47:59,173 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Generate XML for guest factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d with bootdev hd
2013-07-09 12:47:59,173 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Generated XML:
<?xml version="1.0"?>
<domain type="qemu">
  <name>factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d</name>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <uuid>6397eb61-d012-4b78-a22b-43a3f38422af</uuid>
  <clock offset="utc"/>
  <vcpu>1</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
  </os>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <graphics port="-1" type="vnc"/>
    <interface type="bridge">
      <source bridge="virbr0"/>
      <mac address="52:54:00:9e:3a:27"/>
      <model type="virtio"/>
    </interface>
    <input bus="ps2" type="mouse"/>
    <serial type="pty">
      <target port="0"/>
    </serial>
    <serial type="tcp">
      <source mode="bind" host="127.0.0.1" service="1026"/>
      <protocol type="raw"/>
      <target port="1"/>
    </serial>
    <disk device="disk" type="file">
      <target dev="vda" bus="virtio"/>
      <source file="/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body"/>
      <driver name="qemu" type="raw"/>
    </disk>
  </devices>
</domain>

2013-07-09 12:47:59,174 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Base install complete - Doing customization and ICICLE generation
2013-07-09 12:47:59,174 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Customizing image
2013-07-09 12:47:59,182 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Generated XML:
<?xml version="1.0"?>
<domain type="qemu">
  <name>factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d</name>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <uuid>6397eb61-d012-4b78-a22b-43a3f38422af</uuid>
  <clock offset="utc"/>
  <vcpu>1</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
  </os>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <graphics port="-1" type="vnc"/>
    <interface type="bridge">
      <source bridge="virbr0"/>
      <mac address="52:54:00:9e:3a:27"/>
      <model type="virtio"/>
    </interface>
    <input bus="ps2" type="mouse"/>
    <serial type="pty">
      <target port="0"/>
    </serial>
    
    <disk device="disk" type="file">
      <target dev="vda" bus="virtio"/>
      <source file="/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body"/>
      <driver name="qemu" type="raw"/>
    </disk>
  <serial type="tcp"><source mode="bind" host="127.0.0.1" service="1026"/><protocol type="raw"/><target port="1"/></serial></devices>
</domain>

2013-07-09 12:47:59,185 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Collection Setup
2013-07-09 12:47:59,220 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Setting up guestfs handle for factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d
2013-07-09 12:47:59,221 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Adding disk image /var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body
2013-07-09 12:47:59,237 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Launching guestfs
2013-07-09 12:47:59,237 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Grabbing named lock (libguestfs_launch)
2013-07-09 12:47:59,238 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Got named lock (libguestfs_launch)
2013-07-09 12:48:15,313 DEBUG imgfac.ReservationManager.ReservationManager thread(7f42f416) Message: Releasing named lock (libguestfs_launch)
2013-07-09 12:48:15,313 DEBUG oz.Guest.FedoraGuest thread(7f42f416) Message: Inspecting guest OS
2013-07-09 12:48:15,731 DEBUG imagefactory_plugins.TinMan.TinMan.TinMan thread(7f42f416) Message: Cleaning up install artifacts
2013-07-09 12:48:15,731 INFO oz.Guest.FedoraGuest thread(7f42f416) Message: Cleaning up after install
2013-07-09 12:48:15,738 DEBUG imgfac.PersistentImage.BaseImage thread(7f42f416) Message: Getting metadata in class (<class 'imgfac.BaseImage.BaseImage'>) my metadata is (())
2013-07-09 12:48:15,738 DEBUG imgfac.PersistentImage.BaseImage thread(7f42f416) Message: Executing metadata in class (<class 'imgfac.BaseImage.BaseImage'>) my metadata is (('identifier', 'data', 'template', 'icicle', 'status_detail', 'status', 'percent_complete', 'parameters'))
2013-07-09 12:48:15,739 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(7f42f416) Message: Saved metadata for image (9921e75c-218c-4bc9-90ab-35a2b576df5d): {'status': 'FAILED', 'identifier': '9921e75c-218c-4bc9-90ab-35a2b576df5d', 'parameters': {'libvirt_xml': '<?xml version="1.0"?>\n<domain type="qemu">\n  <name>factory-build-9921e75c-218c-4bc9-90ab-35a2b576df5d</name>\n  <memory>1048576</memory>\n  <currentMemory>1048576</currentMemory>\n  <uuid>6397eb61-d012-4b78-a22b-43a3f38422af</uuid>\n  <clock offset="utc"/>\n  <vcpu>1</vcpu>\n  <features>\n    <acpi/>\n    <apic/>\n    <pae/>\n  </features>\n  <os>\n    <type>hvm</type>\n    <boot dev="hd"/>\n  </os>\n  <on_poweroff>destroy</on_poweroff>\n  <on_reboot>destroy</on_reboot>\n  <on_crash>destroy</on_crash>\n  <devices>\n    <graphics port="-1" type="vnc"/>\n    <interface type="bridge">\n      <source bridge="virbr0"/>\n      <mac address="52:54:00:9e:3a:27"/>\n      <model type="virtio"/>\n    </interface>\n    <input bus="ps2" type="mouse"/>\n    <serial type="pty">\n      <target port="0"/>\n    </serial>\n    <serial type="tcp">\n      <source mode="bind" host="127.0.0.1" service="1026"/>\n      <protocol type="raw"/>\n      <target port="1"/>\n    </serial>\n    <disk device="disk" type="file">\n      <target dev="vda" bus="virtio"/>\n      <source file="/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body"/>\n      <driver name="qemu" type="raw"/>\n    </disk>\n  </devices>\n</domain>\n'}, 'icicle': None, 'data': '/var/lib/oz/isos/9921e75c-218c-4bc9-90ab-35a2b576df5d.body', 'status_detail': {'error': 'No operating systems found on the disk', 'activity': 'Base Image build failed with exception.'}, 'template': "<template>\n  <name>f17_x86_64</name>\n  <os>\n    <name>Fedora</name>\n    <version>17</version>\n    <arch>x86_64</arch>\n    <install type='iso'>\n      <iso>http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso</iso>\n    </install>\n    <rootpw>password</rootpw>\n  </os>\n</template>\n", 'percent_complete': 0, 'type': 'BaseImage'}
2013-07-09 12:48:15,739 ERROR imgfac.Builder.Builder thread(7f42f416) Message: Exception encountered in _build_image_from_template thread
2013-07-09 12:48:15,740 ERROR imgfac.Builder.Builder thread(7f42f416) Message: No operating systems found on the disk
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/imgfac/Builder.py", line 132, in _build_image_from_template
    self.os_plugin.create_base_image(self, template, parameters)
  File "/usr/local/lib/python2.7/dist-packages/imagefactory_plugins/TinMan/TinMan.py", line 315, in create_base_image
    builder.base_image.icicle = self.guest.customize_and_generate_icicle(libvirt_xml)
  File "/usr/local/lib/python2.7/dist-packages/oz/RedHat.py", line 1203, in customize_and_generate_icicle
    return self._internal_customize(libvirt_xml, "gen_and_mod")
  File "/usr/local/lib/python2.7/dist-packages/oz/RedHat.py", line 1164, in _internal_customize
    self._collect_setup(modified_xml)
  File "/usr/local/lib/python2.7/dist-packages/oz/RedHat.py", line 394, in _collect_setup
    g_handle = self._guestfs_handle_setup(libvirt_xml)
  File "/usr/local/lib/python2.7/dist-packages/oz/Guest.py", line 1004, in _guestfs_handle_setup
    raise oz.OzException.OzException("No operating systems found on the disk")
OzException: No operating systems found on the disk
2013-07-09 12:48:15,915 DEBUG imgfac.Builder.Builder thread(b1289c2b) Message: BaseImage builder thread (7f42f416) finished - continuing with TargetImage tasks
2013-07-09 12:48:15,915 DEBUG imgfac.BuildDispatcher.BuildDispatcher thread(b1289c2b) Message: Removed builder from BuildDispatcher on notification from image 51977a14-2735-4804-8295-2e218072be8b: FAILED
2013-07-09 12:48:15,915 DEBUG imgfac.PersistentImage.TargetImage thread(b1289c2b) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('base_image_id', 'target'))
2013-07-09 12:48:15,915 DEBUG imgfac.PersistentImage.TargetImage thread(b1289c2b) Message: Executing metadata in class (<class 'imgfac.TargetImage.TargetImage'>) my metadata is (('identifier', 'data', 'template', 'icicle', 'status_detail', 'status', 'percent_complete', 'parameters'))
2013-07-09 12:48:15,916 DEBUG imgfac.FilePersistentImageManager.FilePersistentImageManager thread(b1289c2b) Message: Saved metadata for image (51977a14-2735-4804-8295-2e218072be8b): {'status': 'FAILED', 'identifier': '51977a14-2735-4804-8295-2e218072be8b', 'target': 'EC2', 'parameters': {}, 'icicle': None, 'data': '/var/lib/oz/isos/51977a14-2735-4804-8295-2e218072be8b.body', 'base_image_id': '9921e75c-218c-4bc9-90ab-35a2b576df5d', 'status_detail': {'error': 'The BaseImage (9921e75c-218c-4bc9-90ab-35a2b576df5d) for our TargetImage has failed its build.  Cannot continue.', 'activity': 'Target Image build failed with exception'}, 'template': "<template>\n  <name>f17_x86_64</name>\n  <os>\n    <name>Fedora</name>\n    <version>17</version>\n    <arch>x86_64</arch>\n    <install type='iso'>\n      <iso>http://ftp.jaist.ac.jp/pub/Linux/Fedora/releases/17/Fedora/i386/iso/Fedora-17-i386-netinst.iso</iso>\n    </install>\n    <rootpw>password</rootpw>\n  </os>\n</template>\n", 'percent_complete': 0, 'type': 'TargetImage'}
2013-07-09 12:48:15,916 ERROR imgfac.Builder.Builder thread(b1289c2b) Message: Exception encountered in _customize_image_for_target thread
2013-07-09 12:48:15,916 ERROR imgfac.Builder.Builder thread(b1289c2b) Message: The BaseImage (9921e75c-218c-4bc9-90ab-35a2b576df5d) for our TargetImage has failed its build.  Cannot continue.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/imgfac/Builder.py", line 210, in _customize_image_for_target
    raise ImageFactoryException("The BaseImage (%s) for our TargetImage has failed its build.  Cannot continue." % (self.base_image.identifier))
ImageFactoryException: The BaseImage (9921e75c-218c-4bc9-90ab-35a2b576df5d) for our TargetImage has failed its build.  Cannot continue.

============ Final Image Details ============
UUID: 51977a14-2735-4804-8295-2e218072be8b
Type: target_image
Status: FAILED
Status Details: {'error': 'The BaseImage (9921e75c-218c-4bc9-90ab-35a2b576df5d) for our TargetImage has failed its build.  Cannot continue.', 'activity': 'Target Image build failed with exception'}
root@sudhir-virtual-machine:/home/sudhir/imagefactory# l

**Comment by imcleod** [comment]
Closing as part of a general cleanup of old/stale issues.
