### ISSUE TITLE
Nasty error when no plugins are installed

### ISSUE THREAD

**Issue by dustymabe** [redhat-imaging/imagefactory#373]
I installed imagefactory but no plugins. Then I tried to run a build and I got an error that didn't help much to figure out what the problem was.

My original command was something like: `magefactory --debug base_image --file-parameter install_script koji-f24-build-13885710-base.ks --parameter offline_icicle true  tdl-x86_64.xml`. The error looks like:

```
2016-05-03 08:54:43,686 ERROR imgfac.Builder.Builder thread(751ddf3e) Message: Exception encountered in _build_image_from_template thread
2016-05-03 08:54:43,686 ERROR imgfac.Builder.Builder thread(751ddf3e) Message: 'NoneType' object has no attribute 'create_base_image'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/imgfac/Builder.py", line 132, in _build_image_from_template
    self.os_plugin.create_base_image(self, template, parameters)
AttributeError: 'NoneType' object has no attribute 'create_base_image'
```

This was done using `imagefactory-1.1.8-1.fc24.noarch`

**Comment by ignatenkobrain** [comment]
Did you solve that somehow? I have installed plugins, but that did not help =(

**Comment by ignatenkobrain** [comment]
```
[root@koji-builder02:~/rpms] imagefactory --verbose base_image tdl-x86_64.xml  
{'debug': 0, 'no_ssl': 0, 'no_oauth': 0, 'imgdir': '/var/lib/imagefactory/images', 'ec2_ami_type': 'ebs', 'rhevm_image_format': 'qcow2', 'openstack_image_format': 'qcow2', 'clients': {'mock-key': 'mock-secret'}, 'proxy_ami_id': 'ami-id', 'max_concurrent_local_sessions': 2, 'max_concurrent_ec2_sessions': 4, 'ec2-32bit-util': 'm1.small', 'ec2-64bit-util': 't2.micro', 'image_manager': 'file', 'image_manager_args': {'storage_path': '/var/lib/imagefactory/storage'}, 'tdl_require_root_pw': 0, 'jeos_config': ['/etc/imagefactory/jeos_images/']}
{'verbose': True, 'config': '/etc/imagefactory/imagefactory.conf', 'imgdir': '/var/lib/imagefactory/images', 'timeout': 3600, 'tmpdir': '/tmp', 'plugins': '/etc/imagefactory/plugins.d', 'ec2_32bit_util': 'm1.small', 'ec2_64bit_util': 'm1.large', 'debug': 0, 'output': 'log', 'raw': False, 'command': 'base_image', 'no_ssl': 0, 'no_oauth': 0, 'ec2_ami_type': 'ebs', 'rhevm_image_format': 'qcow2', 'openstack_image_format': 'qcow2', 'clients': {'mock-key': 'mock-secret'}, 'proxy_ami_id': 'ami-id', 'max_concurrent_local_sessions': 2, 'max_concurrent_ec2_sessions': 4, 'ec2-32bit-util': 'm1.small', 'ec2-64bit-util': 't2.micro', 'image_manager': 'file', 'image_manager_args': {'storage_path': '/var/lib/imagefactory/storage'}, 'tdl_require_root_pw': 0, 'jeos_config': ['/etc/imagefactory/jeos_images/'], 'template': <_io.TextIOWrapper name='tdl-x86_64.xml' mode='r' encoding='UTF-8'>, 'parameters': None, 'parameter': None, 'file_parameter': None}
2020-04-22 20:59:41,726 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (RHEVM) loaded...
2020-04-22 20:59:41,726 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (OVA) loaded...
2020-04-22 20:59:41,726 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (TinMan) loaded...
2020-04-22 20:59:41,728 ERROR imgfac.Builder.Builder thread(1f1a177a) Message: Exception encountered in _build_image_from_template thread
2020-04-22 20:59:41,728 ERROR imgfac.Builder.Builder thread(1f1a177a) Message: 'NoneType' object has no attribute 'create_base_image'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/imgfac/Builder.py", line 135, in _build_image_from_template
    self.os_plugin.create_base_image(self, template, parameters)
AttributeError: 'NoneType' object has no attribute 'create_base_image'
```

**Comment by davdunc** [comment]
Experiencing an identical issue 
`'status': 'FAILED'}
2021-06-17 04:07:37,280 ERROR imgfac.Builder.Builder thread(ac28c0c8) Message: Exception encountered in _build_image_from_template thread
2021-06-17 04:07:37,280 ERROR imgfac.Builder.Builder thread(ac28c0c8) Message: 'NoneType' object has no attribute 'create_base_image'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/imgfac/Builder.py", line 135, in _build_image_from_template
    self.os_plugin.create_base_image(self, template, parameters)
AttributeError: 'NoneType' object has no attribute 'create_base_image'

Image build FAILED with error: 'NoneType' object has no attribute 'create_base_image'`

**Comment by davdunc** [comment]
resolved with the documentation to some degree (it got me to my next error). It's not enough to install `imagefactory-plugins`, i failed to install the infrastructure plugins as well.  I resolved the issue by installing all of the imagefactory-plugins-* packages.

**Comment by dustymabe** [comment]
>  I resolved the issue by installing all of the imagefactory-plugins-* packages.

yes, that's what I typically do (did). Install them all.
