### ISSUE TITLE
target_image vsphere fails 'module' object has no attribute 'sudsobject'

### ISSUE THREAD

**Issue by martin-langhoff** [redhat-imaging/imagefactory#394]
The template files are a trivial edit of @imcleod 's `centos.tpl` and `centos.ks` to point to v6 instead of v7.

```
[martin@mlnuc imagefactory]$ sudo imagefactory --debug base_image   --file-parameter install_script ./centos6.ks      ./centos6.tpl 
### succeds, then
[martin@mlnuc vagrant]$ sudo imagefactory --debug target_image --parameter vsphere_vmdk_format standard --id 12074d26-7045-416a-ad0e-d1e1d145a7fd vsphere
2017-01-19 19:07:09,212 DEBUG root thread(MainThread) Message: Unable to find python module, faulthandler... multi-thread tracebacks will not be available. See http://pypi.python.org/pypi/faulthandler/ for more information.
2017-01-19 19:07:09,213 INFO imgfac.PluginManager.PluginManager thread(MainThread) Message: Plugin (OVA) loaded...
(...)
2017-01-19 19:07:09,254 ERROR imgfac.Builder.Builder thread(026b9d45) Message: Exception encountered in _customize_image_for_target thread
2017-01-19 19:07:09,254 ERROR imgfac.Builder.Builder thread(026b9d45) Message: 'module' object has no attribute 'sudsobject'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/imgfac/Builder.py", line 226, in _customize_image_for_target
    self.cloud_plugin = plugin_mgr.plugin_for_target(target)
  File "/usr/lib/python2.7/site-packages/imgfac/PluginManager.py", line 141, in plugin_for_target
    plugin = __import__('%s.%s' % (PKG_STR, plugin_name), fromlist=['delegate_class'])
  File "/usr/lib/python2.7/site-packages/imagefactory_plugins/vSphere/__init__.py", line 17, in <module>
    from vSphere import vSphere as delegate_class
  File "/usr/lib/python2.7/site-packages/imagefactory_plugins/vSphere/vSphere.py", line 31, in <module>
    from VSphereHelper import VSphereHelper
  File "/usr/lib/python2.7/site-packages/imagefactory_plugins/vSphere/VSphereHelper.py", line 23, in <module>
    from psphere.client import Client
  File "/usr/lib/python2.7/site-packages/psphere/client.py", line 37, in <module>
    from psphere import soap, ManagedObject
  File "/usr/lib/python2.7/site-packages/psphere/soap.py", line 91, in <module>
    class ManagedObjectReference(suds.sudsobject.Property):
AttributeError: 'module' object has no attribute 'sudsobject'

Image build FAILED with error: 'module' object has no attribute 'sudsobject'
[martin@mlnuc vagrant]$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
[martin@mlnuc vagrant]$ rpm -qa imagefactory\*
imagefactory-plugins-EC2-JEOS-images-1.1.9-2.fc25.noarch
imagefactory-plugins-RHEVM-1.1.9-2.fc25.noarch
imagefactory-plugins-1.1.9-2.fc25.noarch
imagefactory-1.1.9-2.fc25.noarch
imagefactory-plugins-OVA-1.1.9-2.fc25.noarch
imagefactory-plugins-Docker-1.1.9-2.fc25.noarch
imagefactory-plugins-ovfcommon-1.1.9-2.fc25.noarch
imagefactory-plugins-EC2-1.1.9-2.fc25.noarch
imagefactory-plugins-TinMan-1.1.9-2.fc25.noarch
imagefactory-plugins-vSphere-1.1.9-2.fc25.noarch

```

**Comment by martin-langhoff** [comment]
Updating to latest from updates-testing fixes this. Thanks!
