### ISSUE TITLE
Do not start the program

### ISSUE THREAD

**Issue by garilla22** [redhat-imaging/imagefactory#396]
run your program and observe the following error:
`root@mx:/home/admin/Downloads/imagefactory-master# ./imagefactory
Traceback (most recent call last):
  File "./imagefactory", line 26, in <module>
    from imgfac.ApplicationConfiguration import ApplicationConfiguration
  File "/home/admin/Downloads/imagefactory-master/imgfac/ApplicationConfiguration.py", line 26, in <module>
    from urlgrabber import urlopen
ImportError: No module named urlgrabber
root@mx:/home/admin/Downloads/imagefactory-master# ./im
imagefactory          imagefactoryd         imagefactory_plugins/ imgfac/
root@mx:/home/admin/Downloads/imagefactory-master# ./imagefactoryd
Traceback (most recent call last):
  File "./imagefactoryd", line 23, in <module>
    from imgfac.PersistentImageManager import PersistentImageManager
  File "/home/admin/Downloads/imagefactory-master/imgfac/PersistentImageManager.py", line 17, in <module>
    from ApplicationConfiguration import ApplicationConfiguration
  File "/home/admin/Downloads/imagefactory-master/imgfac/ApplicationConfiguration.py", line 26, in <module>
    from urlgrabber import urlopen
ImportError: No module named urlgrabber`

**Comment by garilla22** [comment]
I make your programm
`root@mx:/home/admin/Downloads/imagefactory-master# make
python setup.py sdist
running sdist
fatal: Not a git repository (or any of the parent directories): .git
running check
warning: sdist: standard file not found: should have one of README, README.txt

reading manifest template 'MANIFEST.in'
writing manifest file 'MANIFEST'
creating imagefactory-1.1.9
creating imagefactory-1.1.9/conf
creating imagefactory-1.1.9/conf/logrotate.d
creating imagefactory-1.1.9/conf/sysconfig
creating imagefactory-1.1.9/imgfac
creating imagefactory-1.1.9/imgfac/picklingtools
creating imagefactory-1.1.9/imgfac/rest
creating imagefactory-1.1.9/scripts
making hard links in imagefactory-1.1.9...
hard linking COPYING -> imagefactory-1.1.9
hard linking cert-ec2.pem -> imagefactory-1.1.9
hard linking imagefactory -> imagefactory-1.1.9
hard linking imagefactory.conf -> imagefactory-1.1.9
hard linking imagefactoryd -> imagefactory-1.1.9
hard linking setup.cfg -> imagefactory-1.1.9
hard linking setup.py -> imagefactory-1.1.9
hard linking conf/imagefactoryd.service -> imagefactory-1.1.9/conf
hard linking conf/logrotate.d/imagefactoryd -> imagefactory-1.1.9/conf/logrotate.d
hard linking conf/sysconfig/imagefactoryd -> imagefactory-1.1.9/conf/sysconfig
hard linking imgfac/ApplicationConfiguration.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/BaseImage.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/BaseImageImporter.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/BuildDispatcher.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Builder.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/CallbackWorker.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/CloudDelegate.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/FactoryUtils.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/FilePersistentImageManager.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/ImageFactoryException.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/MongoPersistentImageManager.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Notification.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/NotificationCenter.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/OSDelegate.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/PersistentImage.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/PersistentImageManager.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/PluginManager.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Provider.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/ProviderImage.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/ReservationManager.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Singleton.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/TargetImage.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Template.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/Version.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/__init__.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/props.py -> imagefactory-1.1.9/imgfac
hard linking imgfac/picklingtools/__init__.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/arraydisposition.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/circularbuffer.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/parsereader.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/pretty.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/simplearray.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/xmldumper.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/xmlloader.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/picklingtools/xmltools.py -> imagefactory-1.1.9/imgfac/picklingtools
hard linking imgfac/rest/OAuthTools.py -> imagefactory-1.1.9/imgfac/rest
hard linking imgfac/rest/RESTtools.py -> imagefactory-1.1.9/imgfac/rest
hard linking imgfac/rest/RESTv2.py -> imagefactory-1.1.9/imgfac/rest
hard linking imgfac/rest/__init__.py -> imagefactory-1.1.9/imgfac/rest
hard linking imgfac/rest/bottle.py -> imagefactory-1.1.9/imgfac/rest
hard linking scripts/imagefactoryd -> imagefactory-1.1.9/scripts
Creating tar archive
removing 'imagefactory-1.1.9' (and everything under it)`
But the problem persists !!!

**Comment by marcindulak** [comment]
As **non** root:

```
sudo su - -c "yum -y install git rpm-build"
git clone https://github.com/redhat-imaging/imagefactory
cd imagefactory
grep BuildRequires imagefactory.spec.in | cut -d':' -f2
sudo su - -c "yum -y install systemd-units python2 python-setuptools"
make rpm
sudo su - -c "yum -y install $HOME/rpmbuild/RPMS/noarch/imagefactory*.rpm"
```
